/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DemoCodeBlock: typeof import('./components/DemoCodeBlock.vue')['default']
    XxAutoComplete: typeof import('@pillar-ui/pillar-ui/autocomplete')['XxAutoComplete']
    XxBadge: typeof import('@pillar-ui/pillar-ui/badge')['XxBadge']
    XxButton: typeof import('@pillar-ui/pillar-ui/button')['XxButton']
    XxCheckbox: typeof import('@pillar-ui/pillar-ui/checkbox')['XxCheckbox']
    XxColor: typeof import('@pillar-ui/pillar-ui/color')['XxColor']
    XxConfirm: typeof import('@pillar-ui/pillar-ui/confirm')['XxConfirm']
    XxDatePicker: typeof import('@pillar-ui/pillar-ui/date-picker')['XxDatePicker']
    XxDrawer: typeof import('@pillar-ui/pillar-ui/drawer')['XxDrawer']
    XxDropdown: typeof import('@pillar-ui/pillar-ui/dropdown')['XxDropdown']
    XxFormPro: typeof import('@pillar-ui/pillar-ui/form-pro')['XxFormPro']
    XxIcon: typeof import('@pillar-ui/pillar-ui/icon')['XxIcon']
    XxInput: typeof import('@pillar-ui/pillar-ui/input')['XxInput']
    XxLoading: typeof import('@pillar-ui/pillar-ui/loading')['XxLoading']
    XxMenu: typeof import('@pillar-ui/pillar-ui/menu')['XxMenu']
    XxModal: typeof import('@pillar-ui/pillar-ui/modal')['XxModal']
    XxNotification: typeof import('@pillar-ui/pillar-ui/notification')['XxNotification']
    XxPagination: typeof import('@pillar-ui/pillar-ui/pagination')['XxPagination']
    XxPopover: typeof import('@pillar-ui/pillar-ui/popover')['XxPopover']
    XxProgress: typeof import('@pillar-ui/pillar-ui/progress')['XxProgress']
    XxRadio: typeof import('@pillar-ui/pillar-ui/radio')['XxRadio']
    XxSelect: typeof import('@pillar-ui/pillar-ui/select')['XxSelect']
    XxSpace: typeof import('@pillar-ui/pillar-ui/space')['XxSpace']
    XxSwitch: typeof import('@pillar-ui/pillar-ui/switch')['XxSwitch']
    XxTable: typeof import('@pillar-ui/pillar-ui/table')['XxTable']
    XxTabs: typeof import('@pillar-ui/pillar-ui/tabs')['XxTabs']
    XxTextarea: typeof import('@pillar-ui/pillar-ui/textarea')['XxTextarea']
    XxTree: typeof import('@pillar-ui/pillar-ui/tree')['XxTree']
    XxUpload: typeof import('@pillar-ui/pillar-ui/upload')['XxUpload']
  }
}
