/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    XxAutoComplete: typeof import('@xx-ui/pillar-ui/autocomplete')['XxAutoComplete']
    XxButton: typeof import('@xx-ui/pillar-ui/button')['XxButton']
    XxInput: typeof import('@xx-ui/pillar-ui/input')['XxInput']
    XxUpload: typeof import('@xx-ui/pillar-ui/upload')['XxUpload']
  }
}
